name: Build and publish

on:
  push:
#on:
#  release:
#    types:
#      - published

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: lolexplain/micro-sip-nextcloud-bridge:latest

#  release-build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.x"
#
#      - name: Build release distributions
#        run: |
#          python -m pip install build
#          python -m build
#
#      - name: Upload distributions
#        uses: actions/upload-artifact@v4
#        with:
#          name: release-dists
#          path: dist/
#
#  pypi-publish:
#    runs-on: ubuntu-latest
#
#    needs:
#      - release-build
#
#    permissions:
#      id-token: write
#
#    environment:
#      name: PyPi
#      url: https://pypi.org/project/micro-sip-nextcloud-bridge/
#
#    steps:
#      - name: Retrieve release distributions
#        uses: actions/download-artifact@v4
#        with:
#          name: release-dists
#          path: dist/
#
#      - name: Publish release distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1